# Generated by Django 5.0.6 on 2024-05-08 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(max_length=4, validators=[django.core.validators.MinLengthValidator(4, 'the field must be 4 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='PasswordGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.TextField(max_length=4, validators=[django.core.validators.MinLengthValidator(4, 'the field must be 4 characters')])),
                ('password', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passwords.password')),
            ],
        ),
    ]
