# Generated by Django 5.0.6 on 2024-05-10 00:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0006_alter_ggpassword_user_delete_gguser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GGPassword',
            new_name='GuessPasswordModel',
        ),
    ]
